language: python
python:
  - "2.7"

before_install:
  - wget https://raw.githubusercontent.com/mozilla/html5-lint/master/html5check.py

script:
  - CHECK=$(for file in *.html; do python ./html5check.py -geh $file; done;)
  - if [[ ! -z "$CHECK" ]]; then echo "$CHECK"; exit 1; fi;
